apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helapp
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: first-app
    repoURL: https://pluhin.github.io/helm-23-23/
    targetRevision: 0.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
