apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-3892301696
  namespace: argocd
spec:
  encryptedData:
    project: AgAEZLsTeraUFUHQDk9cYVi0VJcPAKVnpWW+FCQI7bIKhrOW3TMIaf5DIKqNTmZv6r7g8vWZTM4w6T+YLZl63XfN7151+dLzxvZNGhukG3C8zUv3MEdzB5/zX/B3rHH9ibkBVDDTpC7l9wNMeldbBU7a4ZlT0z4PIRtdtMiaQIUGtHq7ua+z9pvVTI/SnbDG3SX3hDfsmv4oT9Mu0YCaR+0MDsXIyiddHtleNkkiHJK+Wcxf4ll68gu4NnueAyA/MiJ2Rjck0I+Qt0hiF9d3FnWM8H6sRKP7VkMXS3eCQzoY1eiM0DfvSUpH8eU6CHA16i4STnlUFRnxGdxh95iM9Z6vnVmwWjAtKzJr65vYDYUNvrgWijnm8ki4LvtkS7End8PQDbHm1PAj3yW17wbxmIskbXYGxdVzpys6AB7hkcg62iagk1vYZVtAGQTclCF6zyhaK80KUvCpcQoHkM6pZyGCXDZtgZV7t6haDYDTfK+GGyDCmAKULepYVx7jDDwAdbwTJDzwNZ8AuliPwoY9RgYZ8jAjg6evN8NUccQXDkw0b/4mW7GSfcbCrUizSMT19COayfjJ6VxLi/Q9bWdw36zihnqJ8oZ182yJq+Rjp8XIQECk76oU3f/RZm5RLcSk0dhfOFomtCR8mpUn9Y94OrNm84Aa5oooGQ/g20kDlt3QVf+93cOIWi9SY+LgnAsk3qL14GSh1iq4
    type: AgBIJRyvqB+81U7sZlReNMx8+khhlUYcm2I9RcUaD1ZJRhoSM5WBdg2/xutil1nLIxtz2VkKPJwdDGaDxg4F4nlzUI06YRBSrnhR1PQrNm+CveV2LJsS1SjotnVPebShRfVKFWINVBVr2YfPmvMJXPrxpaqJd7BprtYi8aZt6c3DJUZgB7aDyxFJb1mKvbbEBbdvH81UuWdgoIRVG+3fs6hw7eM7hxLntxobfKuMvGdRzyUb2r7lrgeHFL88fvHtNqTCHN7vt9wx5STRdgB+bzuiXVkMO72ZyMcWW5p641h6zjbmLglDbJx+pVHwZ2RUmQeoNGjzlBovHF0nontlSRpUCIGdT0fhfZy2hRw00Hz4s3ZGlK/RnHl2Igpyg4lKy/B1UgrS5PDW0Xny/MHd/5+pOeJmHWuu8g1OkNvVJw4qEPb0V1aBqKAXoDAql+WUnzWpaovkqCaqO5KctQ+r4myjsnnFRr7vlVfdaFb/4KphBNBHEMxu0r3+nmILYG8cn3IALJ5jDnxZCZIM76jDCXAsUwTLLbP8xLFfurovGclTqXfyEMJ3TolTKXTQO0vaRsIqDGBOXwO9CyFDZZHjJCsllErBK7qOIqu9ExfdBCWThwzj4qAeUMWCM/M9xJv5mOIIdBVFqnmuvogj+pckgesuRt8bbXN58vD8USYRTrkFN3WKKtClaGP5C4j8Td3N6UapVgw=
    url: AgCHZkQF8ElblRLLkHgM1mgwWWyagZ7q7l5t0uZ9KtK8bOkjCR9OT3Ku/x2q4bYfayMYY4ctYOE29z4bvoMM7aHVputCv2A08QHLIXa8gUc6/CWrGQ87MBhELrpiZZ+02MJ19geaw3M/5l+uCSnmsKQT5zsf7VoGvB8bs6W5a7IkjrW3iu5/HETnGiexaBQiJwLptmQyxftMtrwnhbF2nj2UVZW7G9BmY8GV1s9Fkw86A1EQTCk1l2o+ExS5MrtyZNYTBK3c3artVqzPeaNHhlOIY9chJUIQxuh5CzfOT7xUIHjd+mvwDe7Ulzpy8JjEhF5I8Ex1aRMJIcaGm9OX5TAxO2aQgLgyeo3M9C1qpt6LR/yWtqKHtcwUhR4zzANzfzx1OsHRrs5J78IAIFOzoNyATI/iCXYCXpkmy8XnkeaNY1xXj2C82XxP2IDpHv/TMPyNlW2sQPobKesvIaYWJpSM36TW533v9+EPd5qmcEBIPtA8Lsney85iFSMudpTKtyiRk9mjqrR3a/NCqxphvREaoMar1CwusQD/OiOs29i+SUyGyrBjvIQDIcArjSqoYNLdGD8yKTySLN4C5qPd2dST82LpY7VUMKbe41iFOz3WNCKR2EzcICXQ+mHPLwLw5zlloclkfJydGG4jvzmnVJbnK1xR/aGrphLG+sH3kHyFa+iHxzu2hnDs0THzAyJ3W6PTbXZqOu0UkVhZXyfYkRw+uE4ceCFktedvLAKQTQDLC/kfACziGOmh6BI5A9H3
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-3892301696
      namespace: argocd
    type: Opaque

