apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-3769429264
  namespace: argocd
spec:
  encryptedData:
    project: AgBguuZIVr7wVT4n7AfnkZBrr7nwEwHlt51LX5gf8k50oco/3h+HYAoBbmBV4jooVszeZJHx4DXELKApC0JCr3ZOzBoWUEBk7A150Ke8u7GCuypHRcm390IuxCMjdiVZ+oMd370v0yNeE3CiGQLDbOq0XZw0M8TliNAJ4i3MSrpcLxusqqiHoY5V2VPMaws4tJYdqwYdWg84KlDy2A7ZuPVQlaORHGxccAECYAbAzad0SCqNI+kmY9SzMFFJJ6rtqZa02aTrGGEVJJQ5by3kT41T3jF7I3hCsA1bioASnYLyoX5EVI0tNTJm8Qcb2O7U4YaGo7slW/5jugRq5Fd0wkUtFMjf6QwG72vXsEvUGhiJRYerXmTSqoAlggDyAw6L8RiQP8u3Ag78NudXAXMHdVPmHuDcmSmxiKX0oHk5iPOT/mF0dkUnuys+ObAGXpyF076I4nn82LqH1vSGrcG5Fqw+OB7rVc2L+fFtGgowsKIZvZje1uklQs7Hshwm89uuAeTvyr35yeQR7e9pFpStjTp6MSpLRQaLHQjxSs7wkEAgX5/uXNI4Fk8+DJPbkxQw7D8iNo3f5xas7NOE77eRkff0ykcS9Gh24gJkNB+n9koL0Okdh86qPTHq6ktM1GJy/yzztEv0+/u5SV44+d1kWQRPsjVU2+ThfWYeHqHOEExRI1OZudhOMVyoWvSyyxo1aC/+KJcy7nl5
    type: AgAStaWNhTPtHB4hkbBw029ZqHuQ1B98XbKOdEIB8YWivIYfpDnIZ/iMysxFKdo/jTVG3v/MR6Lfvc42PjWnfp9zezPFMDDBMyDP8tporwHhhP/xFrjulBajDqbbHORuVhW5bPakGr4vpGL7i7iRh3s44kPDC//5UdY275Q1QhuQqKw3VKKZS3LB4OLiEP+8d+h+HgDjU8Qrs0gKVOSQ4e8YhwJ5M6f4L+Y5nU3v6L0fCsyGERsS7oGyrRfe1mF8twZGWqkZbegWXqBfVzHxM1quQ4Ebs8hMjT9QzPya6aaDylBFsvzIFpvTo7/inywgKJKwo5vY+IAAEFzy9arcGXvhyHJKsLLrkRqrb4qR8N/cPh0zs4SKBmjOaubMYoffLkOK0BvKbKTaoEbSvkl9ZFvxrhwnVkO2blfCEdTekwKKYgLpug02j5uGHv5p2H/wVb+KIoNJWUFyktdyXKXrX8H1vg4yTJ4ce7L8+sLzUe5TIcXapeGC5/bPgJbutWSi+pAye3d6pIZmciiePNbcAWMNfjolWPdCC1p9qPQg0JfpAZAHhsyPw83KvEMObV1hpzaSGZwS+OeLSDcWGCFxsNNEHKrzZE2DyWWDvHy6GDhhBatxhHKwPBwupuhbJ83xb7m/a57oORxSAE1ALvUg325FbZzEOwWEQFyeMld0E6KroRgyq2DcadITg/G8VP3tclPkpK8=
    url: AgDRa/0Y2gd47kge8mgFRJlGpCCJEpZ5yNoyq/IqiYf6EROvwp7uOtAtsfpvmPKqAPfYkZnVNF3yctAJgZDKu2flwrYwS5gE1xNDwMoeUV7DQ8j9ek7aQwEgmHpI/SgO4wdTcqx8XwwZsPkWP+GKRyAopgMf6xnQFGmu3VROZRQeyLe3y6/l6oe8RZh7Ym+5Nwo7hO9l/6TK1kpSW5N2j0aTAwHqAUs8PMJSCLgQdIiRNvnZ/52bbVz+ralFOB0bHFqg2cm939Pb9wmOGWXEUQs8jyptS30di7yJrg34E/0rVErcu3hxe/NqdjZm4bIBSqvOzxiKMRPJDy8Bn0uJeQPTNDyk75OeUGyr9U962lsIPl1BCQqWt/1K41+9LaZwMTdYwMOIpYwLNy30CesP329P2MRRV8l4CCMm+K4uVophTiLSeQ6+AdUBPV4ru/N7p5fsvFpvkVeKzF/Ym4fqk8/5KTZQzgSZKXyqD3n6lVzEk2w59D+6lBpOl1QiinUth5sZFCHc9xKRM47p+2HqUmzHfl9qSF4k/BMbhez9t+kz050pV6fGFLIBQVhB/XIwPRtiyEClQ998llBdTLjPLAIoig5LV7ZmVJWlSsTbRxHiunWvdwyhdYlkJXMG76pYhgyxxm/klPzDkN3rzF7luE0TlM5igDI9Ose7gFiXnKZNMFpNl9kubD9UqFm/awXPkLKHiVNl+hacGDAtTYZs6fTyMNdljZdxFD4UvPZ6ooeAwSsHD3aT9o+U
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-3769429264
      namespace: argocd
    type: Opaque

